### ISSUE TITLE
mailinglogger import error with Python 3.8

### ISSUE THREAD

**Issue by mp24-git** [Simplistix/mailinglogger#17]
The `escape` function in the `cgi` module has been removed, yielding the following error:

```
from cgi import escape
ImportError: cannot import name 'escape' from 'cgi' (/usr/lib64/python3.8/cgi.py)
```

For a fix, see #15

**Comment by cjw296** [comment]
mailinglogger 5.1.0 is out now and on pypi. Thanks for the fixes, I would have liked to have given you some credit in the changelog, but I'm afraid I can't find your name anywhere...
