### ISSUE TITLE
Port to python 3?

### ISSUE THREAD

**Issue by gforcada** [Simplistix/mailinglogger#4]
Hi,

would it be welcomed a port to python 3? Any pointers or preferred way to do the porting? Should it be compatible with both 2 and 3?

Thanks,
Gil

**Comment by cjw296** [comment]
Yes, a port would be welcomed!

Yes, it should be compatible with both 2 and 3 :-)
Sadly, this will be tricky as mailinglogger hits the unicode boundary of an smtp connection.

As a first step, the package could use with being moved to virtualenv and travis-ci, then it would be a case of getting the tests to pass with both 2.7 and 3.4+.

Good luck!

**Comment by gforcada** [comment]
@cjw296 I see that you made this commit https://github.com/Simplistix/mailinglogger/commit/5cd4b3218d886317b2340b9373d10ca445cc4a5f some years ago. Is it worthwhile resurrecting it or do you think is better to start anew?

**Comment by cjw296** [comment]
Where/how did you find that commit? I'd been looking for it to point you at it...
It's probably a good starting point...

**Comment by gforcada** [comment]
@cjw296 I looked at the [forks](https://github.com/Simplistix/mailinglogger/network) and saw your [py3 branch](https://github.com/Simplistix/mailinglogger/compare/master...cjw296:py3) :-)

I will add support for travis and tox so the work can be easily tested. Would you mind enabling travis on this repository?

**Comment by gforcada** [comment]
@cjw296 oh, and while at it maybe [coveralls](https://coveralls.io/) as well? I see that current master is at 98% coverage, awesome work!

**Comment by cjw296** [comment]
Hah! Nice find! :-)

I've enabled travis and coveralls. 98%? Hmm, was 100% when I last checked, be interesting to know what uncovered lines have showed up...

**Comment by hrez** [comment]
@gforcada, Is it python3 yet? :)

**Comment by gforcada** [comment]
@hrez no, I've been working on it on and off, but without enough time to really focus on it :-/

**Comment by cjw296** [comment]
Well, with 4.0.0, we're back up to 100% and the .travis.yml is in a place where adding 3.6 should be easy-ish.

Anyone interested in working on this? I'm deleting my old branch as it's a red herring now.

**Comment by cjw296** [comment]
See #14
